# Generated by Django 2.0.7 on 2018-07-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_icecream_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
