# Generated by Django 2.0.7 on 2018-07-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_icecream_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
